### PR TITLE
[WIP] Meme model and CRUD operations for the backend

### PR DESCRIPTION
**Pull request by devstra**
This PR is a work in progress (not intended for merge), meant to show off what I've done so far based off of @ akshay782's PR #33 .

Since I do not have the full picture, the schema and API endpoints will probably change, but I think this is a good start. Let me know what you think.

### CODE REVIEW

**Review by shubhamcodez — APPROVED** [review]

**Comment by shubhamcodez** [comment]
Definitely great work!

You're going correct.
Meme schema includes
{
The person who posted, 
Caption, 
Url/ Media, 
Like 
comments (I think comments could be mapped from the user who's commenting to the post, I am looking for an efficient solution, to save memory and server load.)
}

**Comment by devstra** [comment]
@shubhamcodez Wouldn't it be better to have the comments stored inside the Meme model and just have a reference to the user who wrote that comment? Correct me if I'm wrong but the comments will only be displayed with the Meme, therefore it makes more sense to me to store them in the Meme model.

I am thinking something like this for the Meme model:
```
  {
    caption: { type: String, required: false },
    mediaUrl: { type: String, match: imageUrlRegex, required: true },
    author: {
      userName: { type: String, required: true },
      profilePicture: { type: String, match: imageUrlRegex, required: false },
    }, // [{ type: Schema.Types.ObjectId, ref: 'User' }] instead ?
    likeCount: { type: Number, default: 0 },
    comments: [
      {
        body: { type: String, required: true },
        author: {
          userName: { type: String, required: true },
          profilePicture: {
            type: String,
            match: imageUrlRegex,
            required: false,
          },
        }, // [{ type: Schema.Types.ObjectId, ref: 'User' }] instead ?
        createdAt: { type: Date, default: Date.now },
      },
    ],
  },
```

**Comment by shubhamcodez** [comment]
Yeah. What you said makes more sense.

**Comment by devstra** [comment]
Since I've made these changes in PR #36 , I'll close this PR now.

**Pull request closed without merging**
