### PR TITLE
Find issues

### PR DESCRIPTION
**Pull request by lekha06**
Updated the readme file with issues.

### CODE REVIEW

**Comment by shubhamcodez** [comment]
I'll merge it when Hacktoberfest starts.

**Comment by shubhamcodez** [comment]
Hey, We have solved these issues in V2 of the project. I'll suggest you make a clone and run the v2 branch and find errors there.

**Review by shubhamcodez — COMMENTED** [review]
Add issues to Issues.md

**Comment by lekha06** [comment]
Okay

**Pull request closed without merging**
